### ISSUE TITLE
add NSAppTransportSecurity to support all sites for testing

### ISSUE THREAD

**Issue by runningfree100** [dequin-cl/WKContentRuleExample#1]
in the info.plist file: 
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>

**Comment by ivanbci** [comment]
Why do you want to allow arbitrary loads?

**Comment by dequin-cl** [comment]
Hi!

Why do you want to allow arbitrary loads?

**Comment by dequin-cl** [comment]
No answer from @runningfree100, I'll close the issue. Feel free to reopen it with more information.
